---
title: "Hackathon prep"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Every transcript needs the following features:
N reads
length of all reads (Separate file)
length of all polya tails (Separate file)
slide parameters for length: max length, proportion at max length
slide parameters for polya: max length, proportion at max length
annotated transcript length, UTR3, UTR5, exonic length, CDS length
GC content

Datasets:
mmu 3T3 Mion, 3T3 PION
hsa HeLa

Output:
half-life

Datasets:
Sharova et al - ESC mice
Eisen et al - 3t3 mice
Tani et al - HeLa human
Supplementary from Tani et al - various human


Data cleaning To do:
1. Decide on which features to use and merge them into one table
1.5. Translate transcript data to gene data
2. Extract relevant columns from the excel sheets to make validation data
3. Merge features and validation by gene names

Data on the LGG server:
Samples:
```
["hsa_dRNA_HeLa_DRB_0h_1",
"mmu_dRNA_3T3_mion_1",
"mmu_dRNA_3T3_PION_1"]
```

bam:
`/home/leect/workspace/slide/samples/{sample}/align/reads.sanitize.noribo.toTranscriptome.sorted.bam`

polya lengths:
`/home/leect/workspace/slide/analysis/slide_polya/{sample}/polyA_read_length.tab`

read lengths:
`/home/leect/workspace/slide/analysis_old/length/{sample}/nanoplen_read_length_non_zero_ids.tab`
